from __future__ import annotations

from typing import Any

from backend.providers.base import TextGenerationRequest


class MockTextGenerationProvider:
    def generate_text(self, request: TextGenerationRequest) -> str:
        user_prompt = request.user_prompt.lower()
        system_prompt = request.system_prompt.lower()
        if "jupyter notebook" in user_prompt:
            return (
                '{"cells":[{"cell_type":"markdown","metadata":{},'
                '"source":["# Mocked solution\\n"]},{"cell_type":"code","metadata":{},'
                '"execution_count":null,"outputs":[],"source":["print(42)\\n"]}],'
                '"metadata":{},"nbformat":4,"nbformat_minor":5}'
            )
        if "beamer" in system_prompt:
            return r"""\documentclass{beamer}
\title{Mocked Slide Deck}
\begin{document}
\begin{frame}
\titlepage
\end{frame}
\begin{frame}{Key Idea}
This smoke-test deck proves the pipeline wrote source.
\end{frame}
\end{document}
"""
        if "cheat" in system_prompt:
            return r"""\documentclass[a4paper]{article}
\usepackage[margin=0.5in]{geometry}
\begin{document}
\section*{Mocked Cheat Sheet}
Dense notes generated by the mocked provider for smoke testing.
\end{document}
"""
        if "latex" in system_prompt:
            return r"""\documentclass{article}
\begin{document}
\section*{Mocked Essay}
This smoke-test essay proves the pipeline wrote source.
\end{document}
"""
        return (
            "def solve():\n"
            "    return 'mocked pipeline output'\n\n"
            "if __name__ == '__main__':\n"
            "    print(solve())\n"
        )


def test_mock_provider(profile: dict[str, Any], _api_key: str) -> dict[str, Any]:
    return {"ok": True, "provider": profile["provider"], "model": profile["model"]}
